# To simulate EB deployment locally
version: '3.8'

services:
  fe: 
    image: aws-ils/fe:${tag}
    container_name: fe
  be:
    image: aws-ils/be:${tag}
    container_name: be
    command: "gunicorn -w 1 -b 0.0.0.0:5000 app:app"
    environment:
     - HOST_MSG=Hosted Locally via Docker Containers on Port 80
  nginx: 
    depends_on: 
      - fe
      - be
    image: aws-ils/nginx:expose1
    container_name: nginx
    ports: 
      - "80:80"
      